<?php if ($row_DIVALL_EX['D011_EX'] == 'WAHR') {include '../../mimes/include/d011/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D012_EX'] == 'WAHR') {include '../../mimes/include/d012/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D013_EX'] == 'WAHR') {include '../../mimes/include/d013/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D021_EX'] == 'WAHR') {include '../../mimes/include/d021/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D022_EX'] == 'WAHR') {include '../../mimes/include/d022/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D023_EX'] == 'WAHR') {include '../../mimes/include/d023/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D031_EX'] == 'WAHR') {include '../../mimes/include/d031/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D032_EX'] == 'WAHR') {include '../../mimes/include/d032/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D033_EX'] == 'WAHR') {include '../../mimes/include/d033/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D041_EX'] == 'WAHR') {include '../../mimes/include/d041/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D042_EX'] == 'WAHR') {include '../../mimes/include/d042/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D043_EX'] == 'WAHR') {include '../../mimes/include/d043/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D051_EX'] == 'WAHR') {include '../../mimes/include/d051/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D052_EX'] == 'WAHR') {include '../../mimes/include/d052/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D053_EX'] == 'WAHR') {include '../../mimes/include/d053/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D061_EX'] == 'WAHR') {include '../../mimes/include/d061/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D062_EX'] == 'WAHR') {include '../../mimes/include/d062/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D063_EX'] == 'WAHR') {include '../../mimes/include/d063/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D071_EX'] == 'WAHR') {include '../../mimes/include/d071/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D072_EX'] == 'WAHR') {include '../../mimes/include/d072/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D073_EX'] == 'WAHR') {include '../../mimes/include/d073/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D081_EX'] == 'WAHR') {include '../../mimes/include/d081/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D082_EX'] == 'WAHR') {include '../../mimes/include/d082/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D083_EX'] == 'WAHR') {include '../../mimes/include/d083/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D091_EX'] == 'WAHR') {include '../../mimes/include/d091/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D092_EX'] == 'WAHR') {include '../../mimes/include/d092/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D093_EX'] == 'WAHR') {include '../../mimes/include/d093/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D101_EX'] == 'WAHR') {include '../../mimes/include/d101/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D102_EX'] == 'WAHR') {include '../../mimes/include/d102/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D103_EX'] == 'WAHR') {include '../../mimes/include/d103/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D111_EX'] == 'WAHR') {include '../../mimes/include/d111/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D112_EX'] == 'WAHR') {include '../../mimes/include/d112/sql-content.php'; }?>
<?php if ($row_DIVALL_EX['D113_EX'] == 'WAHR') {include '../../mimes/include/d113/sql-content.php'; }?>
